# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/jeein_logo.png"
    alt: "KJI"

### Header
header:
  logo:
    image: "assets/img/jeein_logo.png"
    alt: "KJI"

### Social
#social:
  #- title: "Twitter"
    #icon: "fab fa-twitter"
    #url: "http://twitter.com"

  #- title: "Dribbble"
    #icon: "fab fa-dribbble"
    #url: "http://dribbble.com"

  #- title: "Behance"
    #icon: "fab fa-behance"
    #url: "http://behance.com"

### Footer
footer:
  developer: "Developed by <strong>KJI</strong>"
  copyright: "<strong>KJI</strong>. All rights reserved"
